# Generated by Django 5.2.15 on 2026-07-02 15:30

import django.db.models.deletion
from django.db import migrations, models


def seed_default_target_table(apps, schema_editor):
    TargetTable = apps.get_model("workflow", "TargetTable")
    FieldMapping = apps.get_model("workflow", "FieldMapping")
    ModificationRequest = apps.get_model("workflow", "ModificationRequest")

    crdem, _ = TargetTable.objects.get_or_create(
        db_table="ASSALAFDTA.CRDEM",
        defaults={
            "name": "CRDEM",
            "key_column": "NODOSS",
            "is_active": True,
            "description": "Table demande/export avant generation du fichier.",
        },
    )
    FieldMapping.objects.filter(target_table__isnull=True).update(target_table=crdem)
    ModificationRequest.objects.filter(target_table__isnull=True).update(target_table=crdem)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("db_table", models.CharField(max_length=120)),
                ("key_column", models.CharField(default="NODOSS", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="fieldmapping",
            name="workflow_fi_db_colu_4e5f37_idx",
        ),
        migrations.AddField(
            model_name="fieldmapping",
            name="target_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_mappings",
                to="workflow.targettable",
            ),
        ),
        migrations.AddField(
            model_name="modificationrequest",
            name="target_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="workflow.targettable",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldmapping",
            index=models.Index(
                fields=["target_table", "db_column"],
                name="workflow_fi_target__a37cc7_idx",
            ),
        ),
        migrations.RunPython(seed_default_target_table, migrations.RunPython.noop),
    ]
